import React from 'react';
import { Printer } from 'lucide-react';

interface PrintableReportProps {
  title: string;
  entityName?: string;
  generatedBy?: string;
  period?: string;
  generatedDate?: string;
  children: React.ReactNode;
}

export default function PrintableReport({
  title,
  entityName,
  generatedBy,
  period,
  generatedDate,
  children,
}: PrintableReportProps) {
  return (
    <>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { background: white !important; }
          .print-container { box-shadow: none !important; border: none !important; }
        }
      `}</style>

      {/* Screen header with Print button */}
      <div className="no-print mb-6 flex items-center justify-between">
        <div />
        <button
          onClick={() => window.print()}
          className="flex items-center gap-2 px-4 py-2 bg-slate-800 text-white rounded-xl text-sm font-semibold hover:bg-slate-900 transition"
        >
          <Printer size={15} /> Print / Save PDF
        </button>
      </div>

      {/* Printable report content */}
      <div className="print-container bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">

        {/* Report Header */}
        <div className="bg-slate-800 text-white px-8 py-6">
          <h1 className="text-2xl font-bold tracking-wide">{title}</h1>
          <div className="mt-2 flex flex-wrap gap-4 text-sm text-slate-300">
            {entityName && <span>{entityName}</span>}
            {generatedBy && <span>· Generated by: {generatedBy}</span>}
            {period && <span>· Period: {period}</span>}
            {generatedDate && <span>· {generatedDate}</span>}
          </div>
        </div>

        <div className="p-8 space-y-8">
          {children}
        </div>

        {/* Footer */}
        <div className="px-8 py-6 border-t border-slate-200 flex items-center justify-between text-sm text-slate-500">
          <div>
            <span className="font-semibold text-slate-700">Prepared By:</span>{' '}
            <span className="border-b border-slate-400 inline-block w-48">{generatedBy || ''}</span>
          </div>
          <div>
            <span className="font-semibold text-slate-700">Signature:</span>{' '}
            <span className="border-b border-slate-400 inline-block w-48" />
          </div>
        </div>
      </div>
    </>
  );
}
