"use client";
import React, { useEffect, useState } from 'react';
import { Loader2 } from 'lucide-react';
import { getSuperAdminReport, type SuperAdminReport } from '@/services/reportService';
import PrintableReport from '@/components/report/PrintableReport';
import ReportTable from '@/components/report/ReportTable';

const PERIODS = [
  { value: 'DAILY',    label: 'Today'     },
  { value: 'WEEKLY',   label: 'This Week' },
  { value: 'MONTHLY',  label: 'Monthly'   },
  { value: 'YEARLY',   label: 'Yearly'    },
  { value: 'ALL_TIME', label: 'All Time'  },
];

export default function SuperAdminReportsPage() {
  const [report, setReport] = useState<SuperAdminReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [period, setPeriod] = useState('MONTHLY');

  useEffect(() => {
    setLoading(true);
    setReport(null);
    getSuperAdminReport(period)
      .then(setReport)
      .catch((e) => setError(e instanceof Error ? e.message : 'Failed to load report'))
      .finally(() => setLoading(false));
  }, [period]);

  const fmt = (n: number) =>
    new Intl.NumberFormat('en-RW', { style: 'currency', currency: 'RWF', maximumFractionDigits: 0 }).format(n);

  return (
    <div>
      <div className="no-print flex items-center gap-2 mb-4 flex-wrap">
        {PERIODS.map((p) => (
          <button
            key={p.value}
            onClick={() => setPeriod(p.value)}
            className={`px-4 py-1.5 rounded-full text-sm font-semibold border transition ${
              period === p.value
                ? 'bg-teal-600 text-white border-teal-600'
                : 'bg-white text-slate-600 border-slate-200 hover:border-teal-400'
            }`}
          >
            {p.label}
          </button>
        ))}
      </div>

      {loading && (
        <div className="flex items-center justify-center py-32 gap-3 text-slate-400">
          <Loader2 className="animate-spin" size={24} /><span>Loading report...</span>
        </div>
      )}

      {error && !loading && (
        <div className="p-6 bg-rose-50 border border-rose-100 rounded-2xl text-rose-700 text-sm">{error}</div>
      )}

      {!loading && !error && report && (
        <PrintableReport
          title="Platform System Report"
          filename={`platform-report-${period.toLowerCase()}-${new Date().toISOString().slice(0, 10)}.pdf`}
          generatedBy={report.generatedBy}
          generatedDate={report.generatedDate}
          meta={{ rows: [
            { label: 'Report Type',      value: 'Comprehensive Platform Overview' },
            { label: 'Report Period',    value: report.reportPeriod },
            { label: 'Total Pharmacies', value: report.totalPharmacies },
            { label: 'Total Branches',   value: report.totalBranches },
            { label: 'Total Users',      value: report.totalUsers },
            { label: 'Total Patients',   value: report.totalPatients },
            { label: 'Total Orders',     value: report.totalOrders },
            { label: 'Total Revenue',    value: fmt(report.totalRevenue ?? 0) },
            { label: 'Generated By',     value: report.generatedBy },
            { label: 'Generated On',     value: report.generatedDate },
          ]}}
        >
          <ReportTable
            title="Pharmacy Performance"
            columns={['Pharmacy', 'Branches', 'Staff', 'Orders', 'Revenue (RWF)']}
            rows={(report.pharmacyPerformance ?? []).map((r) => [
              r.pharmacyName, r.branches, r.staff, r.orders, fmt(r.revenue ?? 0),
            ])}
            emptyMessage="No pharmacy performance data."
          />

          <ReportTable
            title="Users by Role"
            columns={['Role', 'Count']}
            rows={Object.entries(report.userStatsByRole ?? {}).map(([role, count]) => [role, count])}
            emptyMessage="No user data."
          />

          <ReportTable
            title="Recent Administrative Activity"
            columns={['Action', 'Performed By', 'IP Address', 'Timestamp']}
            rows={(report.recentAuditActivities ?? []).map((r) => [
              r.action, r.userEmail, r.ipAddress, r.timestamp,
            ])}
            emptyMessage="No audit logs."
          />
        </PrintableReport>
      )}
    </div>
  );
}
